version: "3.8"

services:
  llama:
    build:
      context: .
      dockerfile: Dockerfile.llama
    networks:
      - stripe_network
    ports:
      - "11434:11434"

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./vectorstore:/app/vectorstore
    networks:
      - stripe_network
    environment:
      - OLLAMA_URL=http://llama:11434/api/generate

networks:
  stripe_network:
    driver: bridge
