version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - stripe_network
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ./vectorstore:/app/vectorstore
    networks:
      - stripe_network
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
    depends_on:
      - ollama

networks:
  stripe_network:
    external: false
