version: "3.8"

services:
  llama:
    build:
      context: .
      dockerfile: Dockerfile.llama
    container_name: llama_local_server
    networks:
      - stripe_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: llm_stripe_rag
    ports:
      - "8000:8000"
    volumes:
      - ./vectorstore:/app/vectorstore
    networks:
      - stripe_network
    depends_on:
      - llama

networks:
  stripe_network:
    driver: bridge
